version: "3"

services:
  mongo:
    container_name: mongo_database
    restart: always
    volumes:
      - ./docker/mongodb:/data/db
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    